[BUG_FIX] Fixes #6608: CHECK(data != nullptr) causes type checking to fail
apache/incubator-tvm pull request #6610
Opened 2020-10-01 18:08 UTC by electriclilies

Some type rels check that argument types are not null. In certain cases, this can cause the type inferencer to exit prematurely, and the model cannot be run.

Instead of checking that argument types are not null, type rels should just return false, and allow the type checker to determine if the type of arguments cannot be inferred. 

I believe this PR fixes all of the type rels with this issue, however I could have missed some. If you find another, please let me know. 

See issue #6608 for more details.

cc @jwfromm @vegaluisjose @areusch @mbrookhart

2020-10-01 18:32 UTC, mbrookhart requested changes
One logical bug, but otherwise looks great :100:

2020-10-01 18:32 UTC, mbrookhart commented on src/relay/op/tensor/transform.cc
> +  if (data != nullptr) {
if (data == nullptr)

2020-10-01 18:38 UTC, electriclilies commented on src/relay/op/tensor/transform.cc
> +  if (data != nullptr) {
whoopsies

2020-10-01 18:39 UTC, electriclilies commented on src/relay/op/tensor/transform.cc
> +  if (data != nullptr) {
Should be fixed now.

2020-10-01 18:43 UTC, mbrookhart approved these changes

2020-10-01 23:58 UTC, vegaluisjose approved these changes

2020-10-02 13:36 UTC, merged

2020-10-02 13:36 UTC, tqchen commented
Thanks @electriclilies @vegaluisjose @mbrookhart !