Improve AArch64 depthwise convolution through smlal/smlal2 intrinsic
apache/incubator-tvm pull request #6711
Opened 2020-10-19 15:29 UTC by giuseros

- Added an intrinsic to load a single int16x8 vector and produce two
  int32x4 output vectors through smlal/smlal2 instructions

- Changed the NHWC depthwise schedule to accomodate the aforementioned
  intrinsic

Change-Id: I347c3bf98fa8dd87057304dcda0d78e558424c57

2020-10-19 15:29 UTC, giuseros commented
cc @u99127 @anijain2305

2020-10-26 06:41 UTC, FrozenGene commented
I like this change. May I ask two questions?

1. could we make `smlal` / `smlal2` work on convolution too?
2. If we don't use tensorize, do we have method to handle this? For example, add optimization of custom LLVM pass or low detail analyze on tir or llvm ir?

2020-10-26 14:32 UTC, giuseros commented
Hi @FrozenGene 
As for your questions:
1) Yes we can, but there is a issue. It's very hard to have the two quantized strategies (int8 + smull/sadalp vs int16 + smlal/smlal2) available to the auto-tuner at the same time (you already saw [this post](https://discuss.tvm.apache.org/t/quantized-models-and-legalization-pass/8253/3), I will reply there to your comment). In the case of depthwise, we only have the int16 strategy, so the issue does not arise. 
2) Nice you asked, because I am trying to prototype  the idea of a "tir pass" where this  tensorization (and possibly every arm tensorization in `tensor_intrin.py`) happens. My hope is to make it work more or less like `vectorize`. One of the main reasons to have this is to enable Ansor support

2020-10-26 15:07 UTC, FrozenGene commented
> Hi @FrozenGene
> Thanks for your reply!
> 
> 1. Yes we can, but there is a issue. It's very hard to have the two quantized strategies (int8 + smull/sadalp vs int16 + smlal/smlal2) available to the auto-tuner at the same time (you already saw [this post](https://discuss.tvm.apache.org/t/quantized-models-and-legalization-pass/8253/3), I will reply there to your comment). In the case of depthwise, we only have the int16 strategy, so the issue does not arise.
> 2. Nice you asked, because I am trying to prototype  the idea of a "tir pass" where this  tensorization (and possibly every arm tensorization in `tensor_intrin.py`) happens. My hope is to make it work more or less like `vectorize`. One of the main reasons to have this is to enable Ansor support

For ansor, we could make ansor support tensorize (like TensorCore we need tensorize too). However, if we could done it in the llvm / tir, we will make ansor support it easily. If we could lift it as generic pass, I think it will bring benifit to other hardware platform too.

2020-10-28 11:12 UTC, mbaret requested changes

2020-10-28 11:12 UTC, mbaret commented on python/tvm/topi/arm_cpu/tensor_intrin.py
> +            # Lower part of the vector
Higher part of the vector.

2020-10-28 11:12 UTC, mbaret commented on python/tvm/topi/arm_cpu/tensor_intrin.py
> +            # (this will require two different STR instructions, since the
close brackets, STR -> STORE (for those of us who play with strings a lot :) )

2020-10-30 13:47 UTC, mbaret approved these changes
LGTM now. I agree with @FrozenGene that this would be best implemented nearer the LLVM codegen for reusability, but I think this is a good start and demonstrates a worthwhile benefit to performance.

2020-11-02 14:32 UTC, giuseros commented
Hi @mbaret , thanks for the review! 

@FrozenGene , any update on this?

2020-11-03 05:56 UTC, FrozenGene approved these changes

2020-11-03 05:56 UTC, merged

2020-11-03 05:56 UTC, FrozenGene commented
@giuseros @mbaret Thanks, merged now