[TinyFix] Fix cublas batch matmul
apache/incubator-tvm pull request #6715
Opened 2020-10-20 10:41 UTC by sxjscience

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

@comaniac The issue is the same as the cblas_batch_matmul issue in https://github.com/apache/incubator-tvm/pull/6699.

2020-10-20 16:46 UTC, comaniac requested changes
@merrymercy the CI failed at the Ansor tutorial. Would you mind take a look?

2020-10-20 16:46 UTC, comaniac commented on python/tvm/topi/cuda/batch_matmul.py
> +    _ : None
```suggestion
    _ : None
        Output shape argument holder to match the function signature
```

2020-10-20 18:10 UTC, comaniac approved these changes

2020-10-20 20:36 UTC, icemelon9 commented
Why do we need this attribute in `batch_matmul`?

2020-10-20 20:41 UTC, sxjscience commented
The reason is that the code here always assume that there is an `out_shape` argument.  https://github.com/apache/incubator-tvm/blob/461e75bd5ffaf45a0f270998514d444463d11261/python/tvm/relay/op/strategy/generic.py#L685-L686

2020-10-20 22:26 UTC, icemelon9 commented
I checked the implementation. I think we can remove the oshape arg in the topi implementation and we can enable broadcasting at batch axis by default. cc @jwfromm 
https://github.com/apache/incubator-tvm/blob/main/python/tvm/topi/nn/batch_matmul.py#L23

2020-10-22 15:43 UTC, sxjscience commented
Per offline discussion with @icemelon9 , I will have a separate PR to remove the oshape flag directly.

2020-10-22 15:46 UTC, icemelon9 approved these changes
LGTM

2020-10-22 15:46 UTC, merged

2020-10-22 15:46 UTC, icemelon9 commented
Thanks @sxjscience @comaniac