Fix bug of generate-unmatched-brackets in CodeGenC::PrintSSAAssign
apache/incubator-tvm pull request #6887
Opened 2020-11-09 04:16 UTC by Light-of-Hers

Fix the bug discussed in https://github.com/apache/incubator-tvm/issues/6884 @tqchen

2020-11-09 13:50 UTC, tqchen commented
Thanks @Light-of-Hers , can you enhance the code to still remove extra brackets if they match?

The idea would be to add a CheckBracketMatch code that scans the string and use counter to check if the two bracket indeed matches each other (and remove if they do)

2020-11-10 07:55 UTC, Light-of-Hers commented
Updated @tqchen 
Maybe future we can selectively generate surrouding brackets of sub-expressions based the operators' associativity/priority and code-gen context.

2020-11-10 13:28 UTC, tqchen requested changes

2020-11-10 13:28 UTC, tqchen commented on src/target/source/codegen_c.cc
> +  if (s.front() == '(' && s.back() == ')') {
need tyo first check the length to avoid overflow

2020-11-10 13:28 UTC, tqchen commented on src/target/source/codegen_c.cc
> +    int len = s.size();
size_t

2020-11-10 13:28 UTC, tqchen commented on src/target/source/codegen_c.cc
> +    stream << src.substr(1, src.length() - 1);
change this line back as we need to also remove the bracket in the end

2020-11-10 13:28 UTC, tqchen commented on src/target/source/codegen_c.cc
> +static bool CheckOutmostBracketMatch(const std::string& s) {
CheckOutermostBracketMatch

2020-11-10 13:28 UTC, tqchen commented on src/target/source/codegen_c.cc
> +static bool CheckOutmostBracketMatch(const std::string& s) {
Move static after all impl of the non-static function

2020-11-10 14:12 UTC, Light-of-Hers commented
Sorry, some low-level mistakes😂. Is it okay now? @tqchen

2020-11-10 16:03 UTC, tqchen approved these changes

2020-11-10 20:52 UTC, merged

2020-11-10 20:52 UTC, tqchen commented
Thanks @Light-of-Hers !